---
- name: Create modules-load.d directory if it doesn't exist
  file:
    path: /etc/modules-load.d
    state: directory

- name: Create k8s.conf file for modules-load.d
  template:
    src: k8s.modules.conf.j2
    dest: /etc/modules-load.d/k8s.conf

- name: Load overlay and br_netfilter modules
  modprobe:
    name: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: Create sysctl.d directory if it doesn't exist
  file:
    path: /etc/sysctl.d
    state: directory

- name: Create k8s.conf file for sysctl.d
  template:
    src: k8s.sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf

- name: Apply sysctl parameters without reboot
  command: sysctl --system

- name: Display sysctl parameters
  command: sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward